import Head from "next/head";
import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import { Caudex } from "next/font/google";
import { motion  } from "framer-motion"
import Tlinfo from "@/components/timelineinfo"
import styles from "@/styles/Timeline.module.css";

const caudex = Caudex({subsets: ['latin'], weight: '700'})

export default function Timeline() {
  const timelinescrolled = useRef(null);
  const [infofocus, setinfo] = useState<number>(0)

  useEffect(()=>{
    document.addEventListener("wheel", function (e) {
      var variation = parseInt(e.deltaY);
      if(variation > 0){
        setTimeout(()=>{timelinescrolled.current.scrollLeft += 4}, 50);
        setTimeout(()=>{timelinescrolled.current.scrollLeft += 4}, 100);
        timelinescrolled.current.scrollLeft += 6;
      } else {timelinescrolled.current.scrollLeft -= 6;setTimeout(()=>{timelinescrolled.current.scrollLeft -= 4}, 50);setTimeout(()=>{timelinescrolled.current.scrollLeft -= 4}, 100);}
      return false;
    }, true);
  }, [])

  return (
    <>
      <Head>
        <title>FRWC Lore</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.maincontainer}>
        <div className={styles.background} style={{backgroundImage: "url(/images/background.png)", backgroundRepeat: "no-repeat", backgroundSize: "cover"}}></div>
        <div className={styles.container}>
          <h1 className={[styles.title, caudex.className].join(" ")}> FRWC Main Timeline </h1>
          <div className={styles.timelineContainer} ref={timelinescrolled}>
              <motion.div transition={{duration:1.3}} initial={{opacity:0}} whileInView={{opacity:1}} exit={{opacity:0}} viewport={{root: timelinescrolled, margin:"0px -250px 0px -250px"}} className={styles.timelinePiece} style={{marginLeft: "50px", backgroundImage: "url(/images/items/arrow-left.png)"}}> <h2 className={styles.timelineetitle} onClick={() => setinfo(1)}>The Singularity</h2> </motion.div>
              <motion.div transition={{duration:1.3}} initial={{opacity:0}} whileInView={{opacity:1}} exit={{opacity:0}} viewport={{root: timelinescrolled, margin:"0px -250px 0px -250px"}} className={styles.timelinePiece} style={{backgroundImage: "url(/images/items/arrow-center.png)"}}> <h2 className={styles.timelineetitle} onClick={() => setinfo(2)}>Runes Renaissance</h2> </motion.div>
              <motion.div transition={{duration:1.3}} initial={{opacity:0}} whileInView={{opacity:1}} exit={{opacity:0}} viewport={{root: timelinescrolled, margin:"0px -250px 0px -250px"}} className={styles.timelinePiece} style={{backgroundImage: "url(/images/items/arrow-center.png)"}}> <h2 className={styles.timelineetitle} onClick={() => setinfo(3)}>Rumors of the Quantum Shadow </h2> </motion.div>
              <motion.div transition={{duration:1.3}} initial={{opacity:0}} whileInView={{opacity:1}} exit={{opacity:0}} viewport={{root: timelinescrolled, margin:"0px -250px 0px -250px"}} className={styles.timelinePiece} style={{backgroundImage: "url(/images/items/arrow-center.png)"}}> <h2 className={styles.timelineetitle} onClick={() => setinfo(4)}>Factions form</h2> </motion.div>
              <motion.div transition={{duration:1.3}} initial={{opacity:0}} whileInView={{opacity:1}} exit={{opacity:0}} viewport={{root: timelinescrolled, margin:"0px -250px 0px -250px"}} className={styles.timelinePiece} style={{backgroundImage: "url(/images/items/arrow-center.png)"}}> <h2 className={styles.timelineetitle} onClick={() => setinfo(5)}>The Cult is born</h2> </motion.div>
              <motion.div transition={{duration:1.3}} initial={{opacity:0}} whileInView={{opacity:1}} exit={{opacity:0}} viewport={{root: timelinescrolled, margin:"0px -250px 0px -250px"}} className={styles.timelinePiece} style={{backgroundImage: "url(/images/items/arrow-center.png)"}}> <h2 className={styles.timelineetitle} onClick={() => setinfo(6)}>The Great Burning</h2> </motion.div>
              <motion.div transition={{duration:1.3}} initial={{opacity:0}} whileInView={{opacity:1}} exit={{opacity:0}} viewport={{root: timelinescrolled, margin:"0px -250px 0px -250px"}} className={styles.timelinePiece} style={{backgroundImage: "url(/images/items/arrow-center.png)"}}> <h2 className={styles.timelineetitle} onClick={() => setinfo(7)}>The Gate to the Seventh realm is opened</h2> </motion.div>
              <motion.div transition={{duration:1.3}} initial={{opacity:0}} whileInView={{opacity:1}} exit={{opacity:0}} viewport={{root: timelinescrolled, margin:"0px -250px 0px -250px"}} className={styles.timelinePiece} style={{marginRight: "50px", backgroundImage: "url(/images/items/arrow-right.png)"}}> <h2 className={styles.timelineetitle} onClick={() => setinfo(8)}>Shadows are unleashed</h2> </motion.div>
          </div>
          {infofocus > 0 && <Tlinfo e={infofocus} setinfo={setinfo} ></Tlinfo>}
        </div>
      </div>
    </>
  );
}
